version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    laravel9:
        build: 
            context: .
            dockerfile: Dockerfile
        image: laravel9
        container_name: laravel9
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes: 
            - ./src:/var/www/html
            - /var/www/html/vendor/
            - /var/www/html/storage/
            - /var/www/html/bootstrap/
        networks: 
            - app-network
    
    mysql:
        image: mysql:8
        container_name: mysql8
        restart: unless-stopped
        tty: true
        ports: 
            - 3306:3306
        environment: 
            MYSQL_DATABASE: laravel8
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: laravel8
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
        volumes:
            - ./mysql:/var/lib/mysql
    
    nginx:
        image: nginx:1.19.8-alpine
        container_name: nginx1.19
        restart: unless-stopped
        tty: true
        ports: 
            - 8100:80
        volumes: 
            - ./src:/var/www/html
            - ./nginx/conf:/etc/nginx/conf.d
        networks: 
            - app-network